backend:
  name: git-gateway
publish_mode: editorial_workflow
media_folder: "src/assets/uploads"
collections:
  - name: "graphic-design"
    label: "Graphic Design"
    folder: "_posts/graphic-design"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Image", name: "image", widget: "image"}
  - name: "print-design"
    label: "Print Design"
    folder: "_posts/print-design"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Image", name: "image", widget: "image"}